# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sivy.github.io/monkinetic-blog" # the base hostname & protocol for your site

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Monkinetic Weblog
  # avatar: avatar.jpeg
  gravatar: 4fe0ff89158486e907c3a19ded9ac0df
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
   <p>Steve Ivy's Weblog - Since 1999 - XIV Ed.</p>
  footer_text: >
   Copyright Steve Ivy, 1999-2015

  # Icons
  rss: false
  email_address: steveivy@gmail.com  # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "sivy"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "steveivy"
  wordpress:
  youtube:

  # Scripts
  # google_analytics: # Tracking ID, e.g. "UA-000000-01"
  # disqus_shortname:
  # katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
# markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed